version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    command: air -c .air.toml
    environment:
      CONFIG_DIR: /go/src/github.com/ryoshindo/proglog/.proglog
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/ryoshindo/proglog
